### ISSUE TITLE
it doesn't show the content-length

### ISSUE THREAD

**Issue by whwnow** [koa-modules/morgan#1]
when i use the fomat 'dev' like this

``` javascript
app.use(gzip());
app.use(morgan.middleware('dev'));
```

logs show 

```
GET /static/lib/vue/vue.min.js 200 6.866 ms - -
```

**Comment by fundon** [comment]
@whwnow v0.4 is released,you can try it.

**Comment by whwnow** [comment]
@fundon hi, I have updated to 0.4, the problems still exist . is it my usage problem?

**Comment by fundon** [comment]
You need set `morgan.middleware` before `gzip`

**Comment by whwnow** [comment]
it doestn't work. it works right when i remove gzip.  looks like they are
not compatible.

2015-09-24 10:32 GMT+08:00 Fangdun Cai notifications@github.com:

**Comment by fundon** [comment]
See https://github.com/koajs/koa-gzip/blob/master/index.js#L39-L45,

**Comment by whwnow** [comment]
T T, thanks.  I will make a issue to them.

**Comment by haoxins** [comment]
`koa-gzip` can't set the `content-length`, the `body` has been compressed.
So, the origin `content-length` is incorrect
