### ISSUE TITLE
if use proxy, can't show the real ip

### ISSUE THREAD

**Issue by wohugb** [koa-modules/morgan#2]
change getip function in morgan module index.js, and req.headers['x-real-ip'] will show the real ip!

**Comment by fundon** [comment]
@wohugb You can custom the `remote-addr` token, like the below:

``` js
morgan.token('remote-addr', getip)

function getip(req) {
 // do something
}
```

**Comment by JaosnHsieh** [comment]
> @wohugb You can custom the `remote-addr` token, like the below:
> 
> ```js
> morgan.token('remote-addr', getip)
> 
> function getip(req) {
>  // do something
> }
> ```


works well with [proxy-addr](https://github.com/jshttp/proxy-addr)
```javascript
import proxyaddr from 'proxy-addr';
morgan.token('remote-addr', function(req, res) {
  return proxyaddr.all(req);
});
```
