### ISSUE TITLE
async await

### ISSUE THREAD

**Issue by gerardmrk** [koa-modules/morgan#5]
How would you use this with the async-await syntax for Koa v2?

**Comment by fundon** [comment]
See [v1](https://github.com/koa-modules/morgan#1x-100-working-with-morgan-and-koa-v2) on readme file.

If you want to use `async-await`, see https://github.com/koajs/koa/tree/v2.x#example-with-async-functions-babel-required.

**Comment by gerardmrk** [comment]
Ah my mistake! I was using the transpiler, but due to habit, I required 'morgan' instead of 'koa-morgan'. Everything works fine now.
