### ISSUE TITLE
dependencies on github repository

### ISSUE THREAD

**Issue by holymonson** [koa-modules/morgan#7]
Hi, I found in v1.0.0 added `"dependencies": {"morgan": "github:expressjs/morgan"}`, then the morgan npm package cannot be cached or mirrored and has to be pull for github everytime, that broke our massive deployment.

May I know the reason why it changed, or could it be reverted to normal npm versions? Thanks

**Comment by fundon** [comment]
@holymonson Thank you for your report.

I released the [v1.0.1](https://github.com/koa-modules/morgan/releases/tag/v1.0.1).
